window.classicLevels = [
    {
        "level": 1,
        "name": "Classic Level 1",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      ###       ",
            "      #.#       ",
            "      # ####    ",
            "    ###$ $.#    ",
            "    #. $@###    ",
            "    ####$#      ",
            "       #.#      ",
            "       ###      ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 2,
        "name": "Classic Level 2",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #####       ",
            "    #@  # ###   ",
            "    # $$# #.#   ",
            "    # $ ###.#   ",
            "    ###    .#   ",
            "     ##     #   ",
            "     #   #  #   ",
            "     #   ####   ",
            "     #####      ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 3,
        "name": "Classic Level 3",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    #######     ",
            "    #     ###   ",
            "   ##$###   #   ",
            "   # @ $  $ #   ",
            "   # ..# $ ##   ",
            "   ##..#   #    ",
            "    ########    ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 4,
        "name": "Classic Level 4",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "      ####      ",
            "     ##  #      ",
            "     #@$ #      ",
            "     ##$ ##     ",
            "     ## $ #     ",
            "     #.$  #     ",
            "     #..*.#     ",
            "     ######     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 5,
        "name": "Classic Level 5",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "     ####       ",
            "     #@ ###     ",
            "     # $  #     ",
            "    ### # ##    ",
            "    #.# #  #    ",
            "    #.$  # #    ",
            "    #.   $ #    ",
            "    ########    ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 6,
        "name": "Classic Level 6",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "     #######    ",
            "  ####     #    ",
            "  #   .### #    ",
            "  # # #    ##   ",
            "  # # $ $#. #   ",
            "  # #  *  # #   ",
            "  # .#$ $ # #   ",
            "  ##    # # ### ",
            "   # ###.    @# ",
            "   #     ##   # ",
            "   ############ ",
            "                ",
            "                "
        ]
    },
    {
        "level": 7,
        "name": "Classic Level 7",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "     #######    ",
            "    ##  # @#    ",
            "    #   #  #    ",
            "    #$ $ $ #    ",
            "    # $##  #    ",
            "  ### $ # ##    ",
            "  #.....  #     ",
            "  #########     ",
            "                ",
            "                "
        ]
    },
    {
        "level": 8,
        "name": "Classic Level 8",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "      ######    ",
            "    ###    #    ",
            "   ##. $## ##   ",
            "   #..$ $  @#   ",
            "   #.. $ $ ##   ",
            "   ######  #    ",
            "        ####    ",
            "                ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 9,
        "name": "Classic Level 9",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #########   ",
            "    #  ##   #   ",
            "    #   $   #   ",
            "    #$ ### $#   ",
            "    # #...# #   ",
            "   ## #...# ##  ",
            "   # $  $  $ #  ",
            "   #     # @ #  ",
            "   ###########  ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 10,
        "name": "Classic Level 10",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      ######    ",
            "      #    #    ",
            "    ###$$$ #    ",
            "    #@ $.. #    ",
            "    # $...##    ",
            "    ####  #     ",
            "       ####     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 11,
        "name": "Classic Level 11",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "   ####  #####  ",
            "  ##  #  #   #  ",
            "  # $ ####$  #  ",
            "  #  $.... $ #  ",
            "  ##    # @ ##  ",
            "   ##########   ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 12,
        "name": "Classic Level 12",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      #####     ",
            "    ###  @#     ",
            "    #  $. ##    ",
            "    #  .$. #    ",
            "    ### *$ #    ",
            "      #   ##    ",
            "      #####     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 13,
        "name": "Classic Level 13",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      ####      ",
            "      #..#      ",
            "     ## .##     ",
            "     #  $.#     ",
            "    ## $  ##    ",
            "    #  #$$ #    ",
            "    #  @   #    ",
            "    ########    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 14,
        "name": "Classic Level 14",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    ########    ",
            "    #  #   #    ",
            "    # $..$ #    ",
            "    #@$.* ##    ",
            "    # $..$ #    ",
            "    #  #   #    ",
            "    ########    ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 15,
        "name": "Classic Level 15",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "     ######     ",
            "    ##    ##    ",
            "    # $ $$ #    ",
            "    #......#    ",
            "    # $$ $ #    ",
            "    ### @###    ",
            "      ####      ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 16,
        "name": "Classic Level 16",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    ######      ",
            "    #    ###    ",
            "    # $    #    ",
            "  ### $ ## #    ",
            "  #... $   #    ",
            "  #...$#$ ##    ",
            "  #### # $ #    ",
            "     #  @  #    ",
            "     #######    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 17,
        "name": "Classic Level 17",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "   ######       ",
            "   #    #       ",
            "   # $$$##      ",
            "   #  #..###    ",
            "   ##  ..$ #    ",
            "    # @    #    ",
            "    ########    ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 18,
        "name": "Classic Level 18",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "     ########   ",
            "     #   #. #   ",
            "    ##  $...#   ",
            "    #  $ #*.#   ",
            "   ## ##$# ##   ",
            "   #   $  $ #   ",
            "   #   #    #   ",
            "   #######@ #   ",
            "         ####   ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 19,
        "name": "Classic Level 19",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #######     ",
            "    #.... #     ",
            "   ###...$###   ",
            "   #  $#$ $ #   ",
            "   # $$  #$ #   ",
            "   #    #   #   ",
            "   #### @ ###   ",
            "      #####     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 20,
        "name": "Classic Level 20",
        "difficulty": "Beginner",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "     #######    ",
            "     #..$..#    ",
            "     #..#..#    ",
            "     # $$$ #    ",
            "     #  $  #    ",
            "     # $$$ #    ",
            "     #  #@ #    ",
            "     #######    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 21,
        "name": "Classic Level 21",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "      ######    ",
            "      # ...#    ",
            "   ####....#    ",
            "   #  ###$ ###  ",
            "   # $ $  $$ #  ",
            "   #@ $ $    #  ",
            "   #   ###   #  ",
            "   ##### #####  ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 22,
        "name": "Classic Level 22",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "   ########     ",
            "   #      #     ",
            "   # #$$  #     ",
            "   # ...# #     ",
            "   ##...$ ##    ",
            "    # ## $ #    ",
            "    #$  $  #    ",
            "    #  #  @#    ",
            "    ########    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 23,
        "name": "Classic Level 23",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      ######    ",
            "    ###    #### ",
            "    #   $  $  # ",
            "    # $    $ @# ",
            "    ###$$###### ",
            "      #  ..#    ",
            "      #....#    ",
            "      ######    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 24,
        "name": "Classic Level 24",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            " ######   ##### ",
            " #    ### #  .# ",
            " #  $ $ # #...# ",
            " # #  $ ###  .# ",
            " #  $$$   $ @.# ",
            " ###  $  $#  .# ",
            "   #  $#$ #...# ",
            "   ##     #  .# ",
            "    ########### ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 25,
        "name": "Classic Level 25",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "        ######  ",
            "    #####.   #  ",
            "    #  #..## #  ",
            "    #  $..   #  ",
            "    #  # .# ##  ",
            "   ### ##$#  #  ",
            "   # $    $$ #  ",
            "   # #$#  #  #  ",
            "   #@  #######  ",
            "   #####        ",
            "                ",
            "                "
        ]
    },
    {
        "level": 26,
        "name": "Classic Level 26",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "  #########     ",
            "  #   ##  ####  ",
            "  # $        #  ",
            "  ##$### ##  #  ",
            "  #  ## * # ##  ",
            "  # $...... #   ",
            " ## ### . # #   ",
            " #     $###$#   ",
            " #   #    $@#   ",
            " #####$# ####   ",
            "     #   #      ",
            "     #####      ",
            "                "
        ]
    },
    {
        "level": 27,
        "name": "Classic Level 27",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "      ######### ",
            "      #       # ",
            "      # # # # # ",
            "      #  $ $# # ",
            "#######   $   # ",
            "#..#  ## $ $# # ",
            "#..   ## $ $  # ",
            "#..#  ## ###### ",
            "#..# # $ $ #    ",
            "#..     $  #    ",
            "#  ### @ ###    ",
            "#### #####      ",
            "                "
        ]
    },
    {
        "level": 28,
        "name": "Classic Level 28",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "    ####        ",
            "#####  #        ",
            "#  $ $ # #######",
            "#   $  # #*.*.*#",
            "## $ $ ###.*.*.#",
            " #$ $  #  *.*.*#",
            " #@$ $    .*.*##",
            " #$ $  #  *.*.*#",
            "## $ $ ###.*.*.#",
            "#   $  # #*.*.*#",
            "#  $ $ # #######",
            "#####  #        ",
            "    ####        ",
            "                "
        ]
    },
    {
        "level": 29,
        "name": "Classic Level 29",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "    ########    ",
            "    #......#    ",
            "    #  $ # ##   ",
            "    # $ # $ #   ",
            "    ##$ $ $ #   ",
            "     #  @   #   ",
            "     ########   ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 30,
        "name": "Classic Level 30",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "    ##########  ",
            "  ###   .    #  ",
            "  #   ##$##  #  ",
            "  # @$. . .$##  ",
            "  ## $##$## #   ",
            "   #    .   #   ",
            "   ##########   ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 31,
        "name": "Classic Level 31",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "       ######   ",
            "    ####.  @#   ",
            "    #  $$$  #   ",
            "    #.##.##.#   ",
            "    #   $   #   ",
            "    #  $.# ##   ",
            "    ####   #    ",
            "       #####    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 32,
        "name": "Classic Level 32",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    ######      ",
            "    #. ..#      ",
            "    #. $.#      ",
            "   ###  $##     ",
            "   # $  $ #     ",
            "   # #$## #     ",
            "   #   @  #     ",
            "   ########     ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 33,
        "name": "Classic Level 33",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "     ######     ",
            "   ###    ###   ",
            "   #   #$   ### ",
            "   #   $   $$ # ",
            "   # $$ #$    # ",
            "   ##   $   $ # ",
            " ###### #$##### ",
            " #..@ #$  #     ",
            " #.#..  $##     ",
            " #....$# #      ",
            " #....   #      ",
            " #########      ",
            "                "
        ]
    },
    {
        "level": 34,
        "name": "Classic Level 34",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "############### ",
            "#      #      # ",
            "# $ #$ # $##$ # ",
            "# #  $ #      # ",
            "#   ##$#$##$$ # ",
            "# # # ... #   # ",
            "# $  . # .$ # # ",
            "# $#@$...# #  # ",
            "#    . # .  $ # ",
            "# ##.$###$. # # ",
            "# # $..... ## # ",
            "#             # ",
            "############### ",
            "                "
        ]
    },
    {
        "level": 35,
        "name": "Classic Level 35",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "   #########    ",
            "   #   ##  #    ",
            "   # # $ $ #    ",
            "   #  *.#  #    ",
            "   ## #.@.##    ",
            "   ##$###*###   ",
            "   #        #   ",
            "   #   ## # #   ",
            "   ######   #   ",
            "        #####   ",
            "                ",
            "                "
        ]
    },
    {
        "level": 36,
        "name": "Classic Level 36",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "########        ",
            "#      #        ",
            "# $$   ###      ",
            "#  $ $$$ #####  ",
            "## ## ...    ## ",
            " # #@#...###$ # ",
            " # # $...     # ",
            "## # $...$ # ## ",
            "#  ##### ### #  ",
            "#      $   $ #  ",
            "###########  #  ",
            "          ####  ",
            "                "
        ]
    },
    {
        "level": 37,
        "name": "Classic Level 37",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      #####     ",
            "      # @ #     ",
            "      #$$$#     ",
            "   ####   #     ",
            "   #   .#$##    ",
            "   # $.$. .#    ",
            "   #  #.#.##    ",
            "   ########     ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 38,
        "name": "Classic Level 38",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "  ############  ",
            "  #... #     #  ",
            "  #..  # ##  #  ",
            "  #..     #  #  ",
            "  #..  # $## #  ",
            "  #... #$ $  #  ",
            "  ######  $$ #  ",
            "   ##  $ $$  #  ",
            "   #@ $$$  # #  ",
            "   ## $ ##   #  ",
            "    #        #  ",
            "    ##########  ",
            "                "
        ]
    },
    {
        "level": 39,
        "name": "Classic Level 39",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "   #########    ",
            "   #       #    ",
            "   #  $ $ $#    ",
            "   ## #$## #    ",
            "    # .. ..##   ",
            "    ##.. .. #   ",
            "     # ##$# ##  ",
            "     #$ $ $  #  ",
            "     #      @#  ",
            "     #########  ",
            "                ",
            "                "
        ]
    },
    {
        "level": 40,
        "name": "Classic Level 40",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "#####      #### ",
            "#@  ########  # ",
            "## $       $  # ",
            " # # #  ####  # ",
            " #  $   ####$## ",
            " #$ ## # $ $ #  ",
            "## $  $#     #  ",
            "#   #      # #  ",
            "#   #####$####  ",
            "#####   #   #   ",
            "    #...  $ #   ",
            "    #....#  #   ",
            "    #....####   ",
            "    ######      "
        ]
    },
    {
        "level": 41,
        "name": "Classic Level 41",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "        #####   ",
            "    #####   #   ",
            "    # .. $# #   ",
            "    # #.*   #   ",
            "   ## *.#$ ##   ",
            "   # $  $  #    ",
            "   #   ## @#    ",
            "   #########    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 42,
        "name": "Classic Level 42",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "  ##### ####### ",
            "  #   ###  #  # ",
            "  # $     $ @ # ",
            "  ## #$##.##  # ",
            "   #  ...*. $ # ",
            "   # $# #.# # # ",
            "   ##    $    # ",
            "    #  ######## ",
            "    ####        ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 43,
        "name": "Classic Level 43",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "         ###    ",
            "    ######@##   ",
            "    #....#$ ##  ",
            "    #....# $ #  ",
            "    #.... $  #  ",
            "    # ...#   #  ",
            "###### ##### ## ",
            "# $ $   $  #  # ",
            "#    $$   $ $ # ",
            "### $ $ $  #### ",
            "  ##   $ $ #    ",
            "   #  ######    ",
            "   ####         ",
            "                "
        ]
    },
    {
        "level": 44,
        "name": "Classic Level 44",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "     #####      ",
            "   ###   ###    ",
            "  ##  @$ $ #    ",
            "  #  ## ## ##   ",
            "  # $.#.$   #   ",
            "  # #.#*#   #   ",
            "  # $...  ###   ",
            "  ###$# ###     ",
            "    #   #       ",
            "    #####       ",
            "                ",
            "                "
        ]
    },
    {
        "level": 45,
        "name": "Classic Level 45",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "      ####      ",
            "      #  ###### ",
            "      #    #  # ",
            "      # $$    # ",
            "#######$#  #  # ",
            "#  #. .. ###$## ",
            "#  #.#*.$     # ",
            "#  #.#.*# #   # ",
            "# $$....# ##### ",
            "# @$ # ## #     ",
            "# $$$#    #     ",
            "#    ######     ",
            "######          "
        ]
    },
    {
        "level": 46,
        "name": "Classic Level 46",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "####            ",
            "#  ###          ",
            "# $  ###        ",
            "# $ $  ###      ",
            "# $ $ $  ###    ",
            "# $ $ $    #    ",
            "# $ $  #   ##   ",
            "# $  ## $$$ #   ",
            "#@ ####     ##  ",
            "## # #.$$$$$.#  ",
            " # ###.......## ",
            " #   .*******.# ",
            " ####.........# ",
            "    ########### "
        ]
    },
    {
        "level": 47,
        "name": "Classic Level 47",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "  #######       ",
            "  # @#  #####   ",
            "  # $$  $   #   ",
            "  #  #.##$# #   ",
            "  ##$#...   #   ",
            "  ## ...##$##   ",
            "  #  ##.##  #   ",
            "  #  $  $   #   ",
            "  #  #   #  #   ",
            "  ###########   ",
            "                ",
            "                "
        ]
    },
    {
        "level": 48,
        "name": "Classic Level 48",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "     #####      ",
            "     # @ #      ",
            "     # $ #      ",
            "     #$.$#      ",
            "   ###.$.##     ",
            "  ## .$.$.###   ",
            "  #  $.$.$  #   ",
            "  #    .    #   ",
            "  ###########   ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 49,
        "name": "Classic Level 49",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            " #############  ",
            " #  $ $ $.*..#  ",
            " # $ $ $ *...#  ",
            " #  $ $ $.*..#  ",
            " # $ $ $ *...#  ",
            " #  $ $ $.*..#  ",
            " # $ $ $ *...#  ",
            " #  $ $ $.*..#  ",
            " # $ $ $ *...#  ",
            " #  $ $ $.*..#  ",
            " #@$ $ $ *...#  ",
            " #############  ",
            "                "
        ]
    },
    {
        "level": 50,
        "name": "Classic Level 50",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "             #  ",
            "            ##  ",
            "           ###  ",
            "          #   # ",
            "   ######## # # ",
            "  # $ $ $ $   # ",
            " ## #.#.#.#@$#  ",
            "###.......   ## ",
            " ## # # # #$##  ",
            "  # $ $ $ $   # ",
            "   ######## # # ",
            "          #   # ",
            "           ###  ",
            "            ##  "
        ]
    },
    {
        "level": 51,
        "name": "Classic Level 51",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "   #######      ",
            "   #  .$ ###    ",
            "   # .$.$  #    ",
            "   #*$.$.@ #    ",
            "   # .$.$ ##    ",
            "   #  .$  #     ",
            "   ########     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 52,
        "name": "Classic Level 52",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "         #####  ",
            "         #   #  ",
            "########## * ###",
            "#          .   #",
            "# $$$$****$...@#",
            "#          .   #",
            "########## * ###",
            "         #   #  ",
            "         #####  ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 53,
        "name": "Classic Level 53",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "       ####     ",
            "  ######  ##### ",
            "  #@$    $  $ # ",
            "  #$### $ # # # ",
            "  #  #  # $   # ",
            "  # $#    # ### ",
            "  #  $ #$#   #  ",
            "  #......... #  ",
            "  ########   #  ",
            "         #####  ",
            "                ",
            "                "
        ]
    },
    {
        "level": 54,
        "name": "Classic Level 54",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "        ####    ",
            "  #######  #### ",
            "  #    $  ....# ",
            "###   # # ..#.# ",
            "# $$ #  # ....# ",
            "#    # $# ..#.# ",
            "##$###$  ###  # ",
            " #  #  $ $    # ",
            " #    $ $  #$ # ",
            " # $## $ ##  ## ",
            " ## #### # @##  ",
            "  #   #  $ ##   ",
            "  ###     ##    ",
            "    #######     "
        ]
    },
    {
        "level": 55,
        "name": "Classic Level 55",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "  ###########   ",
            "  #    #    #   ",
            "  # $@$$$$$ #   ",
            "  #         #   ",
            "  ##### #####   ",
            "     #.  #      ",
            "     #.  #      ",
            "     #...#      ",
            "     #.  #      ",
            "     #####      ",
            "                ",
            "                "
        ]
    },
    {
        "level": 56,
        "name": "Classic Level 56",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "     #####      ",
            "     # @ #      ",
            "     # $ #      ",
            "   ### . ###    ",
            "   #   *   #    ",
            "   # ***** #    ",
            "   #   *   #    ",
            "   ###$*$###    ",
            "     # . #      ",
            "     # * #      ",
            "     # . #      ",
            "     #####      ",
            "                "
        ]
    },
    {
        "level": 57,
        "name": "Classic Level 57",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            " ############## ",
            " #.           # ",
            " #.$ $ $ $ $  # ",
            " #.#########  # ",
            " #.#.* $ ..$*## ",
            " #.# $ $ *.$@#  ",
            " #.#.  $ ..$$#  ",
            " #.#########.#  ",
            " #.          #  ",
            " #.#$#$#$#$#$#  ",
            " #.          #  ",
            " #############  ",
            "                "
        ]
    },
    {
        "level": 58,
        "name": "Classic Level 58",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            " ############   ",
            " #..  #     ### ",
            " #..  # $  $  # ",
            " #..  #$####  # ",
            " #..    @ ##  # ",
            " #..  # #  $ ## ",
            " ###### ##$ $ # ",
            "   # $  $ $ $ # ",
            "   #    #     # ",
            "   ############ ",
            "                ",
            "                "
        ]
    },
    {
        "level": 59,
        "name": "Classic Level 59",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "        ####    ",
            " ########  #### ",
            " #   ##.....  # ",
            " #  $  ##...# # ",
            " ##  $  ### # # ",
            "  # # $  #    # ",
            "  #  # $  #   # ",
            "  #   # $  #  # ",
            "  #    # $ # ## ",
            "  ####  # $  #  ",
            "     ##  # $ #  ",
            "      ##@#   #  ",
            "       #######  ",
            "                "
        ]
    },
    {
        "level": 60,
        "name": "Classic Level 60",
        "difficulty": "Intermediate",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            " ####      #### ",
            " #..########..# ",
            " #*.*.....*.*.# ",
            " # $ $ $ $ $ $# ",
            " #$ $ $@$ $ $ # ",
            " # $ $ $ $ $ $# ",
            " #$ $ $ $ $ $ # ",
            " #.*.*.....*.*# ",
            " #..########..# ",
            " ####      #### ",
            "                ",
            "                "
        ]
    },
    {
        "level": 61,
        "name": "Classic Level 61",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "      #####     ",
            "     ##   ####  ",
            "     # ..* $ #  ",
            "  #### #.#   #  ",
            "  #    .*.#@##  ",
            "  # #$##$## #   ",
            "  #     $ $ #   ",
            "  ##  #   ###   ",
            "   ########     ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 62,
        "name": "Classic Level 62",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "   ######       ",
            "   #    #       ",
            "   # $  ####    ",
            "   # $*..* #    ",
            "   # *..*$ #    ",
            "   ####  $ #    ",
            "      # @  #    ",
            "      ######    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 63,
        "name": "Classic Level 63",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      #####     ",
            "   ####.  ##    ",
            "   # $.$.  #    ",
            "   #@$# #$ #    ",
            "   # $. .  #    ",
            "   ####$#$ #    ",
            "     #. .  #    ",
            "     #######    ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 64,
        "name": "Classic Level 64",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "  ############  ",
            "  #    ... $ #  ",
            "  # $$$*** $@#  ",
            "  #    ... $ #  ",
            "  ############  ",
            "                ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 65,
        "name": "Classic Level 65",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "   ##########   ",
            "   ##       #   ",
            "   #   #$#$ #   ",
            "   # $$  .$.#   ",
            "   # @###...#   ",
            "   ##########   ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 66,
        "name": "Classic Level 66",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    ####        ",
            "    #  #####    ",
            "   ##$ ##  #    ",
            "   #  $@$  #    ",
            "   #   ##$ #    ",
            "   ###.## ###   ",
            "    #...$ $ #   ",
            "    ##..    #   ",
            "     ########   ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 67,
        "name": "Classic Level 67",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "##### ####      ",
            "#...# #  ####   ",
            "#...###  $  #   ",
            "#....## $  $### ",
            "##....##   $  # ",
            "###... ## $ $ # ",
            "# ##    #  $  # ",
            "#  ## # ### ####",
            "# $ # #$  $    #",
            "#  $ @ $    $  #",
            "#   # $ $$ $ ###",
            "#  ######  ###  ",
            "# ##    ####    ",
            "###             "
        ]
    },
    {
        "level": 68,
        "name": "Classic Level 68",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    #######     ",
            "    #. . .#     ",
            "    # $$$ #     ",
            "    #.$@$.#     ",
            "    # $$$ #     ",
            "    #. . .#     ",
            "    #######     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 69,
        "name": "Classic Level 69",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "        ####    ",
            "  #######  #    ",
            "  #     $  #    ",
            "  #   $##@$#    ",
            "  ##$#...# #    ",
            "   # $...  #    ",
            "   # #. .# ##   ",
            "   #   # #$ #   ",
            "   #$  $    #   ",
            "   #  #######   ",
            "   ####         ",
            "                ",
            "                "
        ]
    },
    {
        "level": 70,
        "name": "Classic Level 70",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "     #########  ",
            "     #   #   #  ",
            "     #       #  ",
            "  #####*### ##  ",
            "  #   ...   #   ",
            "  # # #*###$##  ",
            "  # $    $   #  ",
            "  #####@ #   #  ",
            "      ########  ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 71,
        "name": "Classic Level 71",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "#####           ",
            "#...# #####     ",
            "#...###   #     ",
            "#....   $$##### ",
            "#....  #  #   ##",
            "#..#$#### #$#  #",
            "## $  #     $$ #",
            "#  $# @ $ $$#  #",
            "# $ $ $ #   $ ##",
            "#   #  $ ##   # ",
            "######   ###### ",
            "     #####      ",
            "                ",
            "                "
        ]
    },
    {
        "level": 72,
        "name": "Classic Level 72",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "############### ",
            "###.#      #### ",
            "##..# $  $ #  # ",
            "#...# ## $ #  # ",
            "#.....  #$$   # ",
            "##....$    #$ # ",
            "#### #######  # ",
            "#   $        ## ",
            "#  $ #  $# $ ## ",
            "# $### $ # $$ # ",
            "#   @#  ##    # ",
            "############### ",
            "                "
        ]
    },
    {
        "level": 73,
        "name": "Classic Level 73",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "       ######## ",
            "       #  #   # ",
            " ####### $$...# ",
            " #        #...# ",
            " # ######$#...# ",
            "## #      #...# ",
            "#  # #$ $ ##### ",
            "# # $ $ $ #     ",
            "# @  $ #  #     ",
            "#####$ $$ #     ",
            "    #     #     ",
            "    #######     ",
            "                "
        ]
    },
    {
        "level": 74,
        "name": "Classic Level 74",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "         #####  ",
            "    ######   #  ",
            "  ###    . $ #  ",
            "  # $  #$.#$##  ",
            "  #  #  @.#  #  ",
            "  ## ####.   #  ",
            "   # $  #*####  ",
            "   # ## #.  #   ",
            "   #     .# #   ",
            "   ###$     #   ",
            "     #  #####   ",
            "     ####       ",
            "                "
        ]
    },
    {
        "level": 75,
        "name": "Classic Level 75",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "      ####      ",
            "  #####  #####  ",
            "  #    $   $ #  ",
            "  #  $#$##   #  ",
            "  ### #.*. ###  ",
            "    # ... @#    ",
            "    ## #$###    ",
            "     #   #      ",
            "     #####      ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 76,
        "name": "Classic Level 76",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "      ########  ",
            "   ####    . #  ",
            "   #  $ $ $. #  ",
            "   #  .####.##  ",
            "   # $.$ $ @#   ",
            "   #  .  ####   ",
            "   #######      ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 77,
        "name": "Classic Level 77",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #####       ",
            "    #   #       ",
            "  ###$.$#####   ",
            "  #   . $   #   ",
            "  # ##$## @ #   ",
            "  #   . #####   ",
            "  ### . #       ",
            "    #   #       ",
            "    #####       ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 78,
        "name": "Classic Level 78",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #####       ",
            "    # @ ######  ",
            "    # #..*   #  ",
            "    # ...#   #  ",
            "   ##$## $ $ #  ",
            "   #   #$#####  ",
            "   #   $   #    ",
            "   ##### # #    ",
            "       #   #    ",
            "       #####    ",
            "                ",
            "                "
        ]
    },
    {
        "level": 79,
        "name": "Classic Level 79",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "      ######    ",
            "    ###    ##   ",
            "    #   ##  #   ",
            "  ###$##  # #   ",
            " ##     ..# #   ",
            " #  $#$#*.# #   ",
            " # $$@ #.*# ### ",
            " #  $$ #..#   # ",
            " ##    #..$   # ",
            "  ###$##. # ### ",
            "    #  ###  #   ",
            "    ##     ##   ",
            "     #######    ",
            "                "
        ]
    },
    {
        "level": 80,
        "name": "Classic Level 80",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "      #######   ",
            "      #  #  #   ",
            "      #  $$ #   ",
            " ###### $#  #   ",
            " #...### #  ##  ",
            " #.  #  $ #  #  ",
            " #.    $ $ $ #  ",
            " #.  #  $ #  #  ",
            " #...### #  ##  ",
            " ###### $   #   ",
            "      #@ #  #   ",
            "      #######   ",
            "                "
        ]
    },
    {
        "level": 81,
        "name": "Classic Level 81",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "          ######",
            "          #    #",
            "#####   ### ## #",
            "#.. ##### $  # #",
            "#..     $   $# #",
            "#..  ## ##   # #",
            "#.. ## $ #$ $# #",
            "#.. #     $  # #",
            "#.. #  $ ###$  #",
            "#.. # $ $  $ ###",
            "### ## # $    # ",
            "  #    #@## $ # ",
            "  #########  ## ",
            "          ####  "
        ]
    },
    {
        "level": 82,
        "name": "Classic Level 82",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "        #       ",
            "      #####     ",
            "    ### @ ###   ",
            "    #  $ $  #   ",
            "    # *.*.* #   ",
            "    # .$ $. #   ",
            "    # *.*.* #   ",
            "   ##  $ $  ##  ",
            "  ########  ### ",
            " ###############",
            "     ##   ##    ",
            "                "
        ]
    },
    {
        "level": 83,
        "name": "Classic Level 83",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            " ############## ",
            " # @ * * * #  ##",
            " #$#  * *  #   #",
            " # # * * *     #",
            " # #  * *  ## ##",
            " # # * * * ## # ",
            " # #  * *  ## # ",
            " # # * * * ## # ",
            " # #  * *  ## # ",
            " # # * . * ## ##",
            "## ##########  #",
            "#              #",
            "#   #########  #",
            "#####       ####"
        ]
    },
    {
        "level": 84,
        "name": "Classic Level 84",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "  ############# ",
            "  #    #  ##  # ",
            "  #$$$ # $$  $##",
            "  # $  #  .... #",
            "  #  $  #$.##. #",
            "  #  # $# ....##",
            " ##$ $  #$.##. #",
            " # $  $ @$.... #",
            " #   ###  ######",
            " ##### ####     ",
            "                ",
            "                "
        ]
    },
    {
        "level": 85,
        "name": "Classic Level 85",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "      ######### ",
            "      #       # ",
            "      #  $#$# # ",
            "  ######  # $ # ",
            "  #   # $  $  # ",
            " ## $     ### # ",
            " #   #$####   # ",
            " #    $ ### ### ",
            " #####.. @# ##  ",
            "    #...$ $$ #  ",
            "    #...#    #  ",
            "    #...######  ",
            "    #####       ",
            "                "
        ]
    },
    {
        "level": 86,
        "name": "Classic Level 86",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "####     ####   ",
            "#  #######..### ",
            "# $ $ $  #....# ",
            "# $   $$ #***.# ",
            "# $ $ $  #..*.# ",
            "#  $ $ $ #*.*.# ",
            "## $ $ $ .*.*.##",
            "#  $ $ $ .*.*.@#",
            "#  $ $ $ #*.*.##",
            "# $ $ $  #..*.# ",
            "# $   $$ #***.# ",
            "# $ $ $  #....# ",
            "#  #######..### ",
            "####     ####   "
        ]
    },
    {
        "level": 87,
        "name": "Classic Level 87",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "      #####     ",
            "#######   #     ",
            "#   ##.   #     ",
            "#  $#..  ###    ",
            "##  ...#$$ #####",
            " # $.#.$       #",
            " # $###$## # $ #",
            " #   #     $$# #",
            " ##$$# ##$#$   #",
            " #... $@ $   ###",
            " #...#$#   ###  ",
            " #...  #####    ",
            " #######        ",
            "                "
        ]
    },
    {
        "level": 88,
        "name": "Classic Level 88",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "   ####  ###### ",
            "   #  ####    # ",
            "  ##*   * **  # ",
            "  # $ *    *# # ",
            "  # .   ###   # ",
            "  ######   #@## ",
            "  # * . *  ** # ",
            "  #   #   #   # ",
            "  ##*   * #$# # ",
            "   #  #####   # ",
            "   ####   ##### ",
            "                ",
            "                "
        ]
    },
    {
        "level": 89,
        "name": "Classic Level 89",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    #########   ",
            "    #   #   #   ",
            "    # $$$$$ #   ",
            "   ## $ $ $ #   ",
            "   # $  @   #   ",
            "   # $ #### ##  ",
            "   #  #..... #  ",
            "   ##  ..... #  ",
            "    ##########  ",
            "                ",
            "                "
        ]
    },
    {
        "level": 90,
        "name": "Classic Level 90",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "   #######      ",
            "   #     #      ",
            "   # $ $ ##     ",
            "   #####..##### ",
            "######..*.  $ # ",
            "#  $@$....#$$ # ",
            "#   $ #$###   # ",
            "#####       ### ",
            "    ###  ####   ",
            "      #  #      ",
            "      ####      ",
            "                ",
            "                "
        ]
    },
    {
        "level": 91,
        "name": "Classic Level 91",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "                ",
            "   #####        ",
            "   #   ######   ",
            "   # $ .. $ #   ",
            "   ##$ ..$$@#   ",
            "    #  .. $ #   ",
            "    #########   ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 92,
        "name": "Classic Level 92",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "                ",
            "    #####       ",
            "    #   ######  ",
            "  ###$#.     #  ",
            "  # $ ...# $ #  ",
            "  #@ $.#*$   #  ",
            "  ####    ####  ",
            "     ######     ",
            "                ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 93,
        "name": "Classic Level 93",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "    #####       ",
            "#####   #       ",
            "#   $ @ #       ",
            "#  $ #.#####    ",
            "##$ ##.##  #### ",
            " #  ..... $#  # ",
            " # $##.##  #$ # ",
            " #   #.##     # ",
            " ### $ ##### ## ",
            "   # #$     $ # ",
            "   #    ###   # ",
            "   ###### ##### ",
            "                "
        ]
    },
    {
        "level": 94,
        "name": "Classic Level 94",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "                ",
            "    #######     ",
            "    #  *  #     ",
            "    # @.$ #     ",
            "    # $.  #     ",
            "    #*.***#     ",
            "    #  *  #     ",
            "    # $*$ #     ",
            "    #  .  #     ",
            "    #######     ",
            "                ",
            "                ",
            "                "
        ]
    },
    {
        "level": 95,
        "name": "Classic Level 95",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "  #########     ",
            "  #    #  #     ",
            "### #$  $ ####  ",
            "#  $  ##..#  ###",
            "# #  $ #..$ $  #",
            "# $$  $#..  #  #",
            "##  #  ...#$   #",
            " #$ @ #...# $  #",
            " #    #...$   ##",
            " # ##$ ###   ## ",
            " #   $     ###  ",
            " #  ########    ",
            " ####           ",
            "                "
        ]
    },
    {
        "level": 96,
        "name": "Classic Level 96",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "    ##########  ",
            " ####......  #  ",
            " #   .....#  #  ",
            " #  #...... ##  ",
            " ## ####$##$#   ",
            " #@$  $ $   ### ",
            " # $$    ##   # ",
            " # #  $$##  # # ",
            " #   $  # $$  # ",
            " #  $  $   #$ # ",
            " ####   # $ $ # ",
            "    #   #     # ",
            "    ########### ",
            "                "
        ]
    },
    {
        "level": 97,
        "name": "Classic Level 97",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "      ######### ",
            "      #       # ",
            "      #$ $$$  # ",
            "      #   # $ # ",
            "      #   $@$ # ",
            "    ###$ $ # ## ",
            "    #   $#$# #  ",
            "##### #  #   #  ",
            "#...  # $# ###  ",
            "#.....   # #    ",
            "#.....# $# #    ",
            "########   #    ",
            "       #####    ",
            "                "
        ]
    },
    {
        "level": 98,
        "name": "Classic Level 98",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "  ##### ######  ",
            "  #   ###    #  ",
            " ## $ $ #$ #$#  ",
            " #  $ @ $  $ ## ",
            " # #  ## #....# ",
            " #  ## $ #.##.# ",
            " ##  $    ....# ",
            "  # $$ #$#....# ",
            "  #   #   #$ ## ",
            "  ##### $    #  ",
            "      ####  ##  ",
            "         ####   ",
            "                "
        ]
    },
    {
        "level": 99,
        "name": "Classic Level 99",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "####            ",
            "#  #            ",
            "#  ##########   ",
            "#    ##     #   ",
            "#..#    $$# #   ",
            "#..  ##   $ ### ",
            "#..#  ##$# $  # ",
            "#..   # @$ $  # ",
            "#..#  # $ $   # ",
            "# .   # $ $ ### ",
            "#  #  #   ###   ",
            "#  #    ###     ",
            "#########       ",
            "                "
        ]
    },
    {
        "level": 100,
        "name": "Classic Level 100",
        "difficulty": "Advanced",
        "description": "Classic puzzle challenge",
        "map": [
            "                ",
            "         #####  ",
            "        #     # ",
            "       #  $##  #",
            "      #  #   $ #",
            "#  #  # #  # # #",
            " # #  # $ $  $ #",
            "  ####### #$#  #",
            "  #  $ $      # ",
            "  #@..$ **.###  ",
            "   #......##### ",
            "    ############",
            "                ",
            "                "
        ]
    }
];